# fly.toml app configuration file generated for discord-gemini-bot on 2025-04-19T15:24:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-gemini-bot'
primary_region = 'mia'
kill_signal = 'SIGINT'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '0.5gb'
  cpu_kind = 'shared'
  cpus = 1
